// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID        int64       `db:"id" json:"id"`
	LinkID    int32       `db:"link_id" json:"linkId"`
	ClickedAt time.Time   `db:"clicked_at" json:"clickedAt"`
	IpAddress pgtype.Text `db:"ip_address" json:"ipAddress"`
	UserAgent pgtype.Text `db:"user_agent" json:"userAgent"`
	Referrer  pgtype.Text `db:"referrer" json:"referrer"`
}

type Link struct {
	ID        int32              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Url       string             `db:"url" json:"url"`
	UserID    pgtype.Text        `db:"user_id" json:"userId"`
	CreatedAt time.Time          `db:"created_at" json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
}
