// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateClick(ctx context.Context, arg CreateClickParams) error
	CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error)
	GetLinkByCode(ctx context.Context, code string) (GetLinkByCodeRow, error)
	GetLinkByURL(ctx context.Context, url string) (GetLinkByURLRow, error)
}

var _ Querier = (*Queries)(nil)
